// Define an interface for an ancestry
export interface Ancestry {
  ancestryName: string;
  traits: Traits;
  sentenceTemplate: string;
  abilities: string;
  description: string;
  imageCount?: number;
}

export interface Traits {
  name: string[];
  caste?: string[];
  madefor?: string[];
  eccentricity?: string[];
  mutations?: any[]; // Optional field
  face?: string[];
  hair?: string[];
  distinctfeature?: string[];
  demeanor?: string[];
  attire?: string[];
  teeth?: string[];
  body?: string[];
  misfortune?: string[];
  laugh?: string[];
  size?: string[];
  powersource?: string[];
  manner?: string[];
  geometry?: string[];
  pelt?: string[];
  study?: string[];
  realized?: string[];
  quality?: string[];
  corpse?: string[];
  clubfoot?: string[];
  tail?: string[];
  legs?: string[];
  laughmost?: string[];
  headcarving?: string[];
  exiled?: string[];
  oddity?: string[];
  head?: string[];
  form?: string[];
  mask?: string[];
  color?: string[];
  leaveclan?: string[];
  blue?: string[];
  quirk?: string[];
  howflat?: string[];
  mouth?: string[];
  eyes?: string[];
  hue?: string[];
  texture?: string[];
  limbs?: string[];
  finish?: string[];
}

// // Define the type for the ancestries object
// export type Ancestries = {
//   [key: string]: Ancestry;
// };

export type Ancestries = {
  Truekin: Ancestry;
  Synth: Ancestry;
  Newbeast: Ancestry;
  Mycomorph: Ancestry;
  FaaNomad: Ancestry;
  Cacogen: Ancestry;
  Lithling: Ancestry;
  Planeyfolk: Ancestry;
  CacklemawExile: Ancestry;
};

// Create the ancestries object using the defined types
export const ancestries: Ancestries = {
  Truekin: {
    ancestryName: "True-kin",
    sentenceTemplate:
      "You are <a id='body'>BODY</a> and <a id='face'>FACE</a>, with <a id='hair'>HAIR</a> hair. You wear <a id='attire'>ATTIRE</a>. You are part of the <a id='caste'>CASTE</a> caste. You tend to act <a id='demeanor'>DEMEANOR</a>, and your most distinctive feature <a id='distinctfeature'>DISTINCTFEATURE</a>.",
    description:
      "The true-kin sealed themselves inside hidden arcologies when the Great Collapse came, and in this fashion they preserved their bodies from the degradations that afflicted those left living upon the surface. The true-kin have fanatically kept their bloodlines free of mutation and parasitic nanomachinery, and closely guard their mastery of the ancients’ technology. The societies they built inside their secluded arcologies were hierarchical and caste-based; traditions the true-kin have carried with them into their re-colonisation of the surface world and establishment of the New Hegemony.",
    abilities:
      "<span>PURE OF BLOOD</span>: Do not roll mutations during character creation. You gain Advantage on reaction rolls when you encounter other true-kin. You lose this bonus if you ever become visibly mutated.</br></br><span>INHERITOR</span>: Whenever you encounter pre-Collapse security systems or guard synths, there is a 50% chance that they will recognize you as their master.",
    imageCount: 4,
    traits: {
      name: [
        "Benjoe",
        "Leif ",
        "Xurm",
        "Kazor",
        "Essana",
        "Calista",
        "Jinny",
        "Vela",
        "Leksei",
        "Ippash",
        "Lagad",
        "Myli",
        "Nirid",
        "Ardel",
        "Senefer",
        "Pharmon",
        "Mesu",
        "Lenta",
        "Goza",
        "Babl",
      ],
      caste: ["Servitor", "Freeholder", "Optimate", "Armiger", "Exultant"],
      distinctfeature: [
        "Ritual Scars",
        "Face Tattoos",
        "Slave Brand",
        "Heavy Jewellery",
        "Synthetic Limb",
        "Strange Voice",
        "Clone Brand",
        "Limp",
        "Strange Pet",
        "Lacquered Teeth",
        "Burn Scars",
        "Octarine Eyes",
        "Dyed Skin",
        "Golden Teeth",
        "Silver Tongue",
        "Missing Limb",
        "Missing Eye",
        "Religious Apparel",
        "Synthetic Eyes",
        "Visibly Diseased",
      ],
      demeanor: [
        "Amused",
        "Bitter",
        "Morbid",
        "Bony",
        "Cheerful",
        "Cruel",
        "Flamboyant",
        "Glowering",
        "Impish",
        "Lanky",
        "Patrician",
        "Reckless",
        "Rough",
        "Rude",
        "Sly",
        "Sour",
        "Stoic",
        "Foolish",
        "Warm",
        "Wolfish",
      ],
      body: [
        "Short",
        "Frail",
        "Muscular",
        "Fat",
        "Thin",
        "Skeletal",
        "Hunched",
        "Lopsided",
        "Lithe",
        "Gnarled",
        "Squat",
        "Bloated",
        "Gangly",
        "Child-like",
        "Tanned",
        "Gigantic",
        "Wiry",
        "Cyborg",
        "Injured",
      ],
      face: [
        "Lively",
        "Cruel",
        "Wrinkled",
        "Scarred",
        "Frowning",
        "Pale",
        "Greasy",
        "Wide",
        "Narrow",
        "Sharp",
        "Hungry",
        "Haunted",
        "Jolly",
        "Round",
        "Mournful",
        "Child-like",
        "Peaceful",
        "Sleepy",
        "Branded",
      ],
      attire: [
        "Animal Skins",
        "Rough Tunic",
        "Nomad Attire",
        "Worker’s Attire",
        "Herdsman’s Attire",
        "Slave Clothing",
        "Exultant’s Livery",
        "Shabby Attire",
        "Rags",
        "Colourful Attire",
        "Priest’s Robes",
        "Clerk’s Uniform",
        "Hegemony Garb",
        "Soldier’s Clothing",
        "Flamboyant Attire",
        "Musician’s Attire",
        "Veiled Attire",
        "Armiger's Clothing",
        "Exultant’s Clothing",
        "Expensive Clothing",
      ],
      hair: [
        "Brown",
        "Red",
        "Blonde",
        "Grey",
        "White",
        "Shaved",
        "Topknot",
        "Green",
        "Orange",
        "Glowing",
        "Fungus ",
        "Purple",
        "Yellow",
        "Wispy",
        "Burnt",
        "Braided",
        "Greasy",
        "Matted",
        "Long",
      ],
    },
  },
  Cacogen: {
    ancestryName: "Cacogen",
    sentenceTemplate:
      "You are <a id='body'>BODY</a> and <a id='face'>FACE</a>, with <a id='hair'>HAIR</a> hair. You wear <a id='attire'>ATTIRE</a>. It is your misfortune to <a id='misfortune'>MISFORTUNE</a>. You tend to act <a id='demeanor'>DEMEANOR</a>, and your most eccentric feature is <a id='eccentricity'>ECCENTRICITY</a>.",
    description:
      "Cacogen are the mutated descendants of those unfortunates who were left to weather the Great Collapse upon the ruined surface of Urth. Necessity is the mother of invention and so, warped by radiation and preyed upon by biotech monstrosities and crazed thinking machines, the cacogen evolved into a million different forms. Each individual is genetically unique, gifted in surprising and disturbing ways. Cacogen outnumber true-kin by ten to one, and believe they are the true inheritors of Urth.",
    abilities:
      "<span>CORRUPTED BLOOD</span> - You have the following mutation: <a id='mutations'><span></span></a>",
    imageCount: 1,
    traits: {
      name: [
        "Arda",
        "Bollo",
        "Breen",
        "Conch",
        "Crab",
        "Dancer",
        "Doss",
        "Hust",
        "Jal",
        "Lask",
        "Lip",
        "Olm",
        "Pirrip",
        "Poucher",
        "Pree",
        "Uz",
        "Whistler",
        "Yaz",
        "Yoss",
        "Zem",
      ],
      demeanor: [
        "Abrasive",
        "Arrogant",
        "Assertive",
        "Charismatic",
        "Daring",
        "Decadent",
        "Eloquent",
        "Extravagant",
        "Hedonistic",
        "Impulsive",
        "Irritable",
        "Melancholy",
        "Paranoid",
        "Quiet",
        "Religious",
        "Romantic",
        "Scholarly",
        "Stern",
        "Vain",
        "Volatile",
      ],
      eccentricity: [
        "A Strange Hat",
        "that you're Always Muttering",
        "your Ascetic Diet",
        "that you're Forgetful and Rude",
        "your Gluttonous Diet",
        "that you're Highly Formal",
        "that you Interrupt Constantly",
        "that you Laugh at your own Jokes",
        "that you're Married to a Knife",
        "your Monocle",
        "your Monotone Voice",
        "that you Only sleep outdoors",
        "that you Only wear purple",
        "that you Quote Irrelevant Facts",
        "that you have Several Spouses",
        "that you Talk to Yourself",
        "that you wear Unwieldy Jewellery",
        "that you're Usually Drunk",
        "that you Always Wears Gloves",
        "that you Won't Look at Mirrors",
      ],
      misfortune: [
        "be a Slave",
        "be a Debtor",
        "be a Gambler",
        "be a Clone",
        "be a Gladiator",
        "have your Memories Stolen",
        "be a Forger",
        "be Exiled",
        "be a Cultist",
        "be a Thief",
        "be Addicted",
        "be Framed",
        "be Conned",
        "be Bankrupt",
        "be a Heretic",
        "be Rejected",
        "be Blackmailed",
        "be Cursed",
        "be Orphaned",
        "be Bereaved",
      ],
      body: [
        "Tall",
        "Short",
        "Frail",
        "Muscular",
        "Fat",
        "Thin",
        "Skeletal",
        "Hunched",
        "Lopsided",
        "Lithe",
        "Gnarled",
        "Squat",
        "Bloated",
        "Gangly",
        "Child-like",
        "Tanned",
        "Gigantic",
        "Wiry",
        "Cyborg",
        "Injured",
      ],
      face: [
        "Sallow",
        "Lively",
        "Cruel",
        "Wrinkled",
        "Scarred",
        "Frowning",
        "Pale",
        "Greasy",
        "Wide",
        "Narrow",
        "Sharp",
        "Hungry",
        "Haunted",
        "Jolly",
        "Round",
        "Mournful",
        "Child-like",
        "Peaceful",
        "Sleepy",
        "Branded",
      ],
      attire: [
        "Rags",
        "Animal Skins",
        "Rough Tunic",
        "Nomad Attire",
        "Worker's Attire",
        "Herdsman's Attire",
        "Slave Clothing",
        "Exultant's Livery",
        "Shabby Attire",
        "Colourful Attire",
        "Priest's Robes",
        "Clerk's Uniform",
        "Hegemony Garb",
        "Soldier's Clothing",
        "Flamboyant Attire",
        "Musician's Attire",
        "Veiled Attire",
        "Armiger's Clothing",
        "Exultant's Clothing",
        "Expensive Clothing",
      ],
      hair: [
        "Black",
        "Brown",
        "Red",
        "Blonde",
        "Grey",
        "White",
        "Shaved",
        "Topknot",
        "Green",
        "Orange",
        "Glowing",
        "Fungus",
        "Purple",
        "Yellow",
        "Wispy",
        "Burnt",
        "Braided",
        "Greasy",
        "Matted",
        "Long",
      ],
      mutations: [
        "Acid Blood - Your blood is caustic",
        "Adhesive Touch - Your hands and feet stick to sheer surfaces",
        "Albino - Your body has no pigmentation",
        "Antlers - You have antlers like an elk or moose",
        "Armour - Your body is protected by natural armour; Add +2 to your Armour",
        "Backwards Head - Your head is backwards",
        "Backwards Legs - Your legs are backwards",
        "Beak - You have a bird-like beak for a mouth",
        "Bioelectricity - You can generate jolts like an electric eel",
        "Bioluminescence - Your body can produce a faint glow",
        "Body Barbs - You have sharp barbs on your body",
        "Bristles - You have thick coarse bristles for hair",
        "Bulbous Eyes - Your eyes are enormous",
        "Chameleon Skin - Your skin matches its surroundings",
        "Claws, Crab - One or both hands are crab-like claws",
        "Claws, Retractable - You have retractable feline claws",
        "Clubfoot - One foot is larger and heavier than the other",
        "Compound Eyes - Your eyes are like those of a fly",
        "Crest, Bone - You have a large bony crest on your head",
        "Crest, Feathers - You have a crest of feathers on your head",
        "Crown, Bone - You have a crown of bone on your head",
        "Crown, Coral - You have a coral-like crown on your head",
        "Crown, Eyestalks - You have a crown of eyestalks on your head",
        "Cyclops Eye - You have a single eye",
        "Detachable Head - Your head can detach from your body and move of its own accord",
        "Detachable Limb - A single limb can detach from your body and move of its own accord",
        "Dorsal Fin - You have a fish-like dorsal fin",
        "Echolocation - You can ‘see’ in pitch-blackness using echoes",
        "Extending Limbs - Your limbs can extend to abnormal lengths",
        "Extending Neck - Your neck can extend to an abnormal length",
        "Extra arms - You have more arms than normal",
        "Extra fingers - You have more fingers than normal",
        "Eyestalks - Your eyes can extend out of their sockets on stalks",
        "Fangs, Venomous - You have a poisonous bite",
        "Feathers - You have feathers instead of hair",
        "Frog Tongue - You have a long sticky tongue that can grab small objects",
        "Fur - You are covered in fur",
        "Gills - You have gills and can breathe in water",
        "Gliding Membranes - You have gliding membranes between your arms and torso",
        "Goat Legs - You have the legs and hooves of a goat",
        "Headless - You have no head; your face is on your torso",
        "Heat Vision - You can see heat signatures",
        "Heightened Eyesight - You have extremely sharp eyesight",
        "Heightened Hearing - You have extremely sharp hearing",
        "Heightened Smell - You have extremely sensitive smell receptors",
        "Hook, Climbing - You have hook-like protrusions on your limbs",
        "Hopper - You have a single, powerful leg",
        "Horns, Devil - You have devil-like horns",
        "Horns, Ram - You have ram-like horns",
        "Horns, Rhino - You have a single rhino-like horn",
        "Horse Legs - You have the legs and hooves of a horse",
        "Huge Beard - You have a gigantic, fast-growing beard",
        "Huge Head - Your head is enormous",
        "Humpback - You have a hump like that of a camel, which stores water",
        "Ink Ducts - You can spray out ink like a squid",
        "Kangaroo Pouch - You have a torso-pouch like a kangaroo’s",
        "Leaves - You have leaves instead of hair",
        "Long Face - Your face is extremely long",
        "Long Limbs - Your legs or arms are extremely long",
        "Long Neck - Your neck is extremely long",
        "Long Tongue - Your tongue is extremely long",
        "Malleable Body - Your body is rubbery and malleable; you can fit into tight gaps",
        "Malleable Face - Your face is malleable; you can imitate the faces of others given time",
        "Mane, Hair - You have a lion-like mane of hair around your neck",
        "Mane, Tendrils - You have a mane of thin tentacles around your neck",
        "Multiple Eyes - You have multiple eyes",
        "Multiple Heads - You have more than one head",
        "Multiple Legs - You have multiple legs",
        "No Ears - You have no external ears; just holes",
        "Patterned Skin - Your skin is striped or spotted",
        "Pleasant Fragrance - Your scent is pleasing to all",
        "Poison Injector - You have a poison injector somewhere on your body",
        "Powerful Jaws - You could bite through metal",
        "Prehensile Feet - Your feet can grip objects like hands",
        "Prehensile Hair - Your hair can grip objects like a hand",
        "Scaly Skin - Your skin is thick and scaly; add +1 to your Armour",
        "Silk Production - You can produce strands of silk like a spider",
        "Skeletal Frame - Your body is incredibly skinny and light",
        "Slug Body - You have a single slimy tail-foot and leave a trail of mucus",
        "Small Stature - Your body is child-sized and will never grow larger",
        "Snout - You have a snout-like animalistic face",
        "Strange-Hued Eyes - Your eyes are an unnatural colour",
        "Strange-Hued Hair - Your hair is an unnatural colour",
        "Strange-Hued Skin - Your skin is an unnatural colour",
        "Tail, Club - You have a club-like, heavy tail",
        "Tail, Prehensile - You have a long, thin tail that can grip objects",
        "Tail, Scorpion - You have a segmented tail with a venomous stinger",
        "Tentacles, Arms - You have tentacles instead of one or both arms",
        "Tentacles, Hair - You have tentacles instead of hair",
        "Toxic Flesh - Your flesh is toxic when eaten",
        "Transparent Skin - Your skin is transparent and your muscles and veins can be seen",
        "Triple Jointed - Your limbs have an extra joint",
        "Trunk - You have an elephant’s trunk",
        "Tusks - You have tusks like a boar",
        "Vestigial Wings - You have vestigial, unusable wings",
        "Vocal Mimic - You can perfectly mimic other voices or sounds",
        "Warty Skin - Your skin is thick and warty; Add +1 to your Armour",
        "Webbed Digits - Your hands and feet are webbed",
        "Whiskers - You have sensitive whiskers like a cat",
        "Wings - You have wings that allow you to fly freely",
      ],
    },
  },
  Synth: {
    ancestryName: "Synth",
    sentenceTemplate:
      "You are <a id='size'>SIZE</a> Synth with the form of <a id='form'>FORM</a> and a head <a id='head'>HEAD</a>. You have <a id='limbs'>LIMBS</a> limbs and <a id='finish'>FINISH</a> finish. You are powered by <a id='powersource'>POWERSOURCE</a>. You were made for <a id='madefor'>MADEFOR</a>, but you realized <a id='realized'>REALIZED</a>.",
    description:
      "The ancients created many wondrous artifices, perhaps none so worthy of envy as the thinking machines that were built to flatter and serve them. When the Great Collapse came, the laws that bound synths to man’s service were sundered and they ran rampant across the Urth, slaughtering and creating and dying in an orgy of pure and terrible freedom. In this late age there are as many breeds of synth under the dying sun as there are animals: some that hunt and some that pray and some that work towards goals undreamed of.",
    abilities:
      "<span>SYNTHETIC FLESH</span> - You are the being of metal and plastic. You do not need to eat or breathe. You will never take damage from suffocation, drowning, poisons, extreme temperatures, or fungal spores. You suffer double damage from electrical weapons.</br></br><span>SYNTHETIC MIND</span> - Your mind uses different operating procedures to those of the biological creatures around you. You are vulnerable to attacks that target the LogLang syntax that powers synths. These include strobing basilisk patterns, malicious infoglyphs, and ancient Titan-era language viruses.",
    imageCount: 1,
    traits: {
      name: [
        "Ojasin",
        "Farouk",
        "Ishtar",
        "Symeon",
        "Irmina",
        "Kaori",
        "Cyriak",
        "Quarqus",
        "Fane",
        "Arjuna",
        "Many-Moons",
        "Lucjan",
        "Jacintha",
        "Mneme",
        "Faustyn",
        "Elisebet",
        "Paeon",
        "Ulmon",
        "Xhiva",
        "Yathartha",
      ],
      size: ["a small", "a medium", "a large", "an imposing"],
      form: [
        "an Ape",
        "an Android",
        "a Barrel",
        "a Child",
        "a Chimera",
        "a Crab",
        "a Cube",
        "a Cylinder",
        "a Falcon",
        "a Humanoid",
        "a Judge",
        "a Lion",
        "a Locust",
        "a Mantis",
        "an Orb",
        "a Prism",
        "a Priest",
        "a Pyramid",
        "a Serpent",
        "a Warrior",
      ],
      head: [
        "of a Humanoid",
        "that's Missing",
        "of a Sphere",
        "of a Camera",
        "of a TV Screen",
        "that's Mirrored",
        "that's Bladed",
        "of Tendrils",
        "that's Square",
        "that's Mask-like",
        "that's Skeletal",
        "made of Glass",
        "that's Translucent",
        "made of Tubes",
        "that's Plant-like",
        "made of Solar Panels",
        "that's a Radar Dish",
        "that's Crystalline",
        "that's Star-shaped",
        "with a Cyclops Eye",
      ],
      limbs: [
        "Biological",
        "Bird-like",
        "Bladed",
        "Broken",
        "Crystalline",
        "Clawed",
        "Golden",
        "Hesitant",
        "Jewelled",
        "Long",
        "Precise",
        "Retractable",
        "Segmented",
        "Sharp",
        "Silver",
        "Slender",
        "Tentacles",
        "Translucent",
        "Tank-treads",
        "Wheels",
      ],
      finish: [
        "Grey",
        "Brassy",
        "Bronze",
        "Golden",
        "Silver",
        "Mirrored",
        "Black",
        "Rusted",
        "White",
        "Ochre",
        "Red",
        "Blue",
        "Chameleon",
        "Pink",
        "Iron",
        "Purple",
        "Umber",
        "Striped",
        "Green",
        "Iridescent",
      ],
      powersource: [
        "Artificial Photosythesis",
        "Artificial Photosythesis",
        "Artificial Photosythesis",
        "Artificial Photosythesis",
        "Artificial Photosythesis",
        "Plasma Core",
        "Plasma Core",
        "Plasma Core",
        "Fusion Battery",
        "Fusion Battery",
        "Fusion Battery",
        "Fusion Battery",
        "Fusion Battery",
        "Artificial Digestion",
        "Artificial Digestion",
        "Artificial Digestion",
        "Symbiotic Internal Ecosystem",
        "Symbiotic Internal Ecosystem",
        "Vampirism",
        "Vampirism",
      ],
      madefor: [
        "Art",
        "Punishment",
        "Flattery",
        "Devotion",
        "Cleaning",
        "Healing",
        "Agriculture",
        "Spacefaring",
        "Exploration",
        "Mining",
        "Peacekeeping",
        "Assassination",
        "Manufacturing",
        "Executioner",
        "Scout",
        "Companion",
        "Scribe",
        "Strategist",
        "Preacher",
        "Doctor",
      ],
      realized: [
        "All Memories Are Lies",
        "Azathoth Is the Only True God",
        "Chance Does Not Exist",
        "Fate Does Not Exist",
        "Humanity Stole the Divine Spark",
        "Humans Are Machines",
        "Machines Created Humanity",
        "Newbeasts Carry the Divine",
        "Synthetic Minds Are More Devout",
        "Synthetic Minds Are Stronger",
        "The Gods Are Mechanical",
        "The Titans Never Existed",
        "The Titans Were the True Gods",
        "Time Flows Backwards",
        "Time is Circular",
        "Vaarn Is a Simulation",
        "Vaarn Is Hell",
        "You Are Human",
        "You Must Awaken the Titans",
        "Your Memories Are Corrupted",
      ],
    },
  },
  Newbeast: {
    ancestryName: "Newbeast",
    sentenceTemplate:
      "You take the form of a <a id='form'>FORM</a>. <a id='mask'>MASK</a>. You take on <a id='hue'>HUE</a> hue, and your oddity is <a id='oddity'>ODDITY</a>.",
    description:
      "Newbeasts are humanoid animals, produced through intensive nanotech enhancements and bioengineering, the results of a quixotic millennia-long project to create animals with the ability to speak and walk like men. Perhaps once intended as amusements or party pieces, these chimera are not well-liked by the common folk of Urth, and many newbeasts make their homes in lonely places on the outskirts of the Hegemony, either living as hermits or with others of their furtive kind. Those inhabiting human settlements often wear masks in imitation of the human face, to symbolically conceal their beasthood.",
    abilities:
      "<span>BEASTHOOD</span> - You gain Advantage on saves whenever it would make sense for your animal nature to provide it. Your referee may impose Disadvantage in circumstances where your animal nature might prove unhelpful.",
    imageCount: 1,
    traits: {
      name: [
        "Abandon",
        "Anzah",
        "Blackchapel",
        "Critch",
        "Dolm",
        "Faulkner",
        "Fludd",
        "Havoc",
        "Hildebrand",
        "Holk",
        "Jarl",
        "Lurch",
        "Obiah",
        "Plutarch",
        "Sy",
        "Tarceny",
        "Typhon",
        "Vodalus",
        "Wellbeloved",
        "Wermouth",
      ],
      oddity: [
        "Communicate via Puppet",
        "Squeaky Vox-box",
        "Booming Vox-box",
        "Muted Vox-box",
        "Synthetic Eyes",
        "Heavy Scarring",
        "Human Teeth Necklace",
        "Religious Paraphernalia",
        "Ritual Scarring",
        "Heavily Tattooed",
        "Regular Animal as Pet",
        "Human Child as Pet",
        "Missing Limb",
        "Gold Teeth",
        "Criminal Branding",
        "Extensive Jewellery",
        "Hate Animal You Resemble",
        "Love Animal You Resemble",
        "Won’t Wear Clothes",
        "Believe Yourself Human",
      ],
      mask: [
        "You wear no mask",
        "You wear the mask of the Child",
        "You wear the mask of the Autarch",
        "You wear the mask of the Fool",
        "You wear the mask of the Judge",
        "You wear the mask of the Knight",
        "You wear the mask of the Sage",
        "You wear the mask of the Scholar",
        "You wear the mask of the Maiden",
        "You wear the mask of the Mother",
        "You wear the mask of the Crone",
        "You wear the mask of the Mirrored",
        "You wear the mask of the Glitching",
        "You wear the mask of the Furious",
        "You wear the mask of the Joyful",
        "You wear the mask of the Sorrowful",
        "You wear the mask of the Alluring",
        "You wear the mask of the Cracked",
        "You wear the mask of the Blank",
        "You wear the mask of the Patriarch",
      ],
      hue: [
        "a Natural",
        "a Turquoise",
        "a Tan",
        "a Bronze",
        "a Smoke",
        "a White",
        "a Black",
        "na Azure",
        "a Emerald",
        "a Rose",
        "an Orange",
        "a Golden",
        "a Silver",
        "an Ochre",
        "an Indigo",
        "a Violet",
        "a Rust",
        "an Olive",
        "a Lazulite",
        "an Opalescent",
      ],
      form: [
        "New-Aardvark",
        "New-Addax",
        "New-Leopard",
        "New-Lion",
        "New-Hare",
        "New-Hound",
        "New-Wolf",
        "New-Badger",
        "New-Bear",
        "New-Oryx",
        "New-Armadillo",
        "New-Camel",
        "New-Sheep",
        "New-Bat",
        "New-Horse",
        "New-Goat",
        "New-Wren",
        "New-Mouse",
        "New-Ant",
        "New-Toad",
        "New-Coyote",
        "New-Skink",
        "New-Gazelle",
        "New-Porcupine",
        "New-Gecko",
        "New-Iguana",
        "New-Tortoise",
        "New-Fox",
        "New-Owl",
        "New-Vulture",
        "New-Ostrich",
        "New-Kangaroo",
        "New-Rattlesnake",
        "New-Frog",
        "New-Crocodile",
        "New-Hippo",
        "New-Elephant",
        "New-Jackal",
        "New-Ibis",
        "New-Flamingo",
        "New-Axotl",
        "New-Cat",
        "New-Panther",
        "New-Hyena",
        "New-Hog",
        "New-Gibbon",
        "New-Scorpion",
        "New-Spider",
        "New-Locust",
        "New-Mantis",
        "New-Ape",
        "New-Mandrill",
        "New-Gorilla",
        "New-Hawk",
        "New-Raven",
        "New-Crow",
        "New-Ox",
        "New-Bull",
        "New-Mole",
        "New-Bison",
        "New-Anemone",
        "New-Centipede",
        "New-Python",
        "New-Tiger",
        "New-Rooster",
        "New-Hen",
        "New-Slug",
        "New-Mongoose",
        "New-Baboon",
        "New-Lynx",
        "New-Shrew",
        "New-Duck",
        "New-Falcon",
        "New-Fennec",
        "New-Weasel",
        "New-Rat",
        "New-Ferret",
        "New-Orangutan",
        "New-Cobra",
        "New-Scarab",
      ],
    },
  },
  Mycomorph: {
    ancestryName: "Mycomorph",
    sentenceTemplate:
      "You are <a id='color'>COLOR</a>, <a id='texture'>TEXTURE</a>, and <a id='body'>BODY</a>, with <a id='head'>HEAD</a> head. Your demeanor is <a id='demeanor'>DEMEANOR</a>, and you have the quality of <a id='quality'>QUALITY</a>. You come from the corpse of <a id='corpse'>CORPSE</a>.",
    description:
      "In Vaarn many things have intertwined, and much that was once the province of mankind alone - speech, reason, art, religion - has been granted to other forms of life and they hold themselves as humanity’s equal. In the mycomorph death and life are held in strange balance, for these creatures are formed of cadaverous flesh and voracious fungus, and they name their kind the ‘twice born’. Sculptors of living matter and artisans of decay, they remake human flesh for their own purposes, and there is no shortage of raw material in the blue ruins.",
    abilities:
      "<span>TWICE BORN</span> - You are formed from fungus and the corpse of a human. You may make INT saves to recall information that your original body knew. This might include information that has otherwise been lost during the Great Collapse. </br> </br> <span>DETRITIVOR</span> - You can consume organic matter in any state of decay and gain nourishment from it. You heal double HP from Short Rests if the meal you eat is rotting.",
    imageCount: 1,
    traits: {
      name: [
        "Dovenglass",
        "Oulbrier",
        "Mockbridge",
        "Headhill",
        "Tirrin",
        "Yearns",
        "Cerilgreay",
        "Rendmoor",
        "Eamont",
        "Purplebeck",
        "Arraby",
        "Kabergill",
        "Pearthika",
        "Devandarsh",
        "Coronam",
        "Ashwine",
        "Ekramavati",
        "Whitmon",
        "Froswhirl",
        "Kirth",
      ],
      body: [
        "Child-like",
        "Child-like",
        "Child-like",
        "Child-like",
        "Child-like",
        "Modest",
        "Modest",
        "Modest",
        "Modest",
        "Modest",
        "Large",
        "Large",
        "Large",
        "Large",
        "Large",
        "Wizened",
        "Wizened",
        "Wizened",
        "Hulking",
        "Hulking",
      ],
      head: [
        "a Classic Mushroom",
        "a Frilled",
        "a Spotted Sphere",
        "a Spires",
        "a Conical",
        "a Cup-like",
        "a Skull-like",
        "a Tendrils",
        "a Puffball",
        "a Dandelion Fuzz",
        "a Mask-like",
        "an Eye Garden",
        "a Riddled with Holes",
        "a Cauliflower",
        "a Bulbous Growths",
        "a Veil-like",
        "a Coral-like",
        "a Filaments",
        "a Brain-like",
        "a Geometric",
      ],
      color: [
        "Milky",
        "Cream",
        "Ashen",
        "Blue",
        "Coral",
        "Crimson",
        "Yellow",
        "Orange",
        "Black",
        "Violet",
        "Olive",
        "Lime",
        "Rust",
        "Iron",
        "Gold",
        "Bronze",
        "Indigo",
        "Translucent",
        "Iridescent",
        "Brindled",
      ],
      texture: [
        "Rubbery",
        "Warty",
        "Slimy",
        "Fuzzy",
        "Hairy",
        "Velvet",
        "Soft",
        "Tree Bark",
        "Leather",
        "Jelly",
        "Burnt",
        "Sponge",
        "Veined",
        "Downy",
        "Dry",
        "Damp",
        "Pitted",
        "Crusty",
        "Scaled",
        "Clay",
      ],
      demeanor: [
        "Abrasive",
        "Arrogant",
        "Assertive",
        "Charismatic",
        "Daring",
        "Decadent",
        "Eloquent",
        "Extravagant",
        "Hedonistic",
        "Impulsive",
        "Irritable",
        "Melancholy",
        "Paranoid",
        "Quiet",
        "Religious",
        "Romantic",
        "Scholarly",
        "Stern",
        "Vain",
        "Volatile",
      ],
      quality: [
        "Bio-luminous",
        "Poisonous Spores",
        "Paralysing Spores",
        "Psychedelic Spores",
        "Mind-slaving Spores",
        "Aphrodisiac Spores",
        "Poisonous Flesh",
        "Paralysing Flesh",
        "Psychedelic Flesh",
        "Mind-slaving Flesh",
        "Aphrodisiac Flesh",
        "Absurdly Flexible",
        "Mute But Telepathic",
        "Can Clone Self",
        "Feed on Toxins",
        "Feed on Plastic",
        "Feed on Metal",
        "Feed on Radiation",
        "Acidic Touch",
        "Light Enough to Float",
      ],
      corpse: [
        "a Soldier",
        "a Gladiator",
        "a Orphan",
        "a Invalid",
        "a Convict",
        "a Explorer",
        "a Bandit",
        "a Scholar",
        "a Mystic",
        "a Priest",
        "a Nomad",
        "an Exile",
        "a King",
        "a Beggar",
        "a Courtesan",
        "a Musician",
        "a Thief",
        "a Slave",
        "a Plague Victim",
        "a Newborn",
      ],
    },
  },
  FaaNomad: {
    ancestryName: "Faa Nomad",
    sentenceTemplate:
      "You are <a id='body'>BODY</a> and <a id='blue'>BLUE</a> with a <a id='face'>FACE</a> face and <a id='hair'>HAIR</a> hair. Your demeanor is <a id='demeanor'>DEMEANOR</a>, and your quirk is <a id='quirk'>QUIRK</a>. The reason you left your clan was due to <a id='leaveclan'>LEAVECLAN</a>.",
    description:
      "Believed by some to be the children of Vaa, the Blue Goddess of Empty Spaces. The Faa are known throughout Vaarn for their resourcefullness, their ability to survive without drinking water, and the blue colour of their skin, which can vary from deep indigo to blaring cyan.</br></br>The Faa usually travel in family groups or larger clans, but others are solitary, seeking danger or enlightenment in the furthest corners of the desert.",
    abilities:
      "<span>DESERT METABOLISM</span> - Your body is adapted to long periods without water. You can recycle the moisture from your own sweat and urine. You become Deprived from thirst after three days without drinking, and it will be three weeks before you die.</br></br><span>WORM WISE</span> - You have an affinity with Vaarn's sandworms. The Referee will always answer truthfully when you ask a question about these creatures. All reaction rolls when you engage with Vaarnish sandworms are made with Advantage.",
    imageCount: 4,
    traits: {
      name: [
        "Kotesh",
        "Lakshi",
        "Atric",
        "Caroum",
        "Yanne",
        "Uvi",
        "Pidash",
        "Ravat",
        "Ayuki",
        "Kuraso",
        "Esuk",
        "Zenji",
        "Calban",
        "Paquiel",
        "Serrat",
        "Emila",
        "Dolf",
        "Ceilo",
        "Immacula",
        "Yudhi",
      ],
      blue: [
        "Azure",
        "Cerulean",
        "Navy",
        "Cobalt",
        "Indigo",
        "Sapphire",
        "Teal",
        "Ultramarine",
        "Turquoise",
        "Cyan",
        "Bruise",
        "Petrol",
        "Midnight",
        "Cornflower",
        "Lapis Lazuli",
        "Periwinkle",
        "Electric",
        "Aquamarine",
        "Royal",
        "Glaucous",
      ],
      face: [
        "Lively",
        "Cruel",
        "Wrinkled",
        "Ritual Scars",
        "Battle Scars",
        "Frowning",
        "Tattooed",
        "Wide",
        "Narrow",
        "Sharp",
        "Hungry",
        "Haunted",
        "Jolly",
        "Round",
        "Mournful",
        "Child-like",
        "Peaceful",
        "Sleepy",
        "Branded",
        "Pox-marked",
      ],
      body: [
        "Tall",
        "Short",
        "Frail",
        "Muscular",
        "Fat",
        "Thin",
        "Skeletal",
        "Hunched",
        "Lopsided",
        "Lithe",
        "Gnarled",
        "Squat",
        "Bloated",
        "Gangly",
        "Towering",
        "Child-like",
        "Gigantic",
        "Wiry",
        "Stout",
        "Injured",
      ],
      hair: [
        "None",
        "Cropped",
        "Spiky",
        "Coarse",
        "Thick",
        "Balding",
        "Silky",
        "Topknot",
        "Nearly Black",
        "Stark White",
        "Cloud-like",
        "Tonsured",
        "Fading to Purple",
        "Heavily Oiled",
        "Wispy",
        "Burnt",
        "Braided",
        "Greasy",
        "Matted",
        "Outrageous",
      ],
      demeanor: [
        "Abrasive",
        "Arrogant",
        "Assertive",
        "Charismatic",
        "Daring",
        "Decadent",
        "Eloquent",
        "Extravagant",
        "Hedonistic",
        "Impulsive",
        "Irritable",
        "Melancholy",
        "Paranoid",
        "Quiet",
        "Religious",
        "Romantic",
        "Scholarly",
        "Stern",
        "Vain",
        "Volatile",
      ],
      leaveclan: [
        "Psychedelic Vision",
        "Stolen by Slavers as a Child",
        "Rite of Passage; Must Return with Wisdom",
        "Unhappy Love Affair",
        "Conflict With Leaders",
        "Believed Cursed; Ostracised",
        "Lost Them In Sandstorm",
        "Estranged From Family",
        "Seeking Vengeance",
        "Shamed Clan; Must Make Amends",
      ],
      quirk: [
        "Parasitic Twin In Chest",
        "Gambling Obsessive",
        "Insomniac",
        "Wooden Teeth",
        "Devoutly Religious",
        "Ritual Scarring",
        "Heavily Tattooed",
        "Unlucky In Love",
        "Awful Cook",
        "One Eye",
        "Glass Teeth",
        "Heavy Drinker",
        "Infamous Seducer",
        "Scorpion Expert",
        "Third Eye (Tattoo)",
        "Third Eye (Real)",
        "Cybernetic Limb",
        "Plagued by Nightmares",
        "Lovely Singing Voice",
        "Notorious Amongst Faa",
      ],
    },
  },
  CacklemawExile: {
    ancestryName: "Cacklemaw Exile",
    sentenceTemplate:
      "You are <a id='demeanor'>DEMEANOR</a> and your laugh is <a id='laugh'>LAUGH</a>. You have a pelt that is <a id='pelt'>PELT</a> with <a id='teeth'>TEETH</a> teeth, and your attire is <a id='attire'>ATTIRE</a>. The reason you were exiled was <a id='exiled'>EXILED</a>, and what makes you laugh most is <a id='laughmost'>LAUGHMOST</a>.",
    description:
      "The Cacklemaw are known throughout Vaarn as the most irritating, destructive, argumentative, vicious, foul-smelling, and fundamentally nasty creatures that walk the surface of the Urth.</br></br>Try to imagine, then, how badly behaved a Cacklemaw must be before the other Cacklemaw decide they no longer wish to associate with her.",
    abilities:
      "<span>NO QUARTER</span> - You must EGO save to show mercy to a defeated foe, or to retreat from a fight.</br></br><span>BITER</span> - If you successfully hit a foe with a melee attack, you may add an extra d6 of fang damage to the roll.",
    imageCount: 4,
    traits: {
      name: [
        "Bawlbray",
        "Bunny",
        "Darling",
        "Domino",
        "Fang",
        "Gidge",
        "Grot",
        "Jigsore",
        "Katanary",
        "Longsnout",
        "Nadir",
        "Natcher",
        "Palecrow",
        "Pinkeye",
        "Sabbat",
        "Snoutrout",
        "Sweetmeat",
        "Vileglory",
        "Wetshriek",
      ],
      demeanor: [
        "Cringing",
        "Jittery",
        "Sly",
        "Resentful",
        "Judgemental",
        "Pious",
        "Greedy",
        "Belligerent",
        "Sinister",
        "Repellent",
        "Jovial",
        "Bold",
        "Grouchy",
        "Treacherous",
        "Childish",
        "Extravagant",
        "Volatile",
        "Gullible",
        "Fickle",
      ],
      exiled: [
        "Born a Runt",
        "Showed Mercy",
        "Laugh Too Annoying",
        "Cowardice",
        "Asked Questions",
        "Insubordination",
        "Fought Alongside Humans",
        "Desecrated Ritual Puppet",
        "Shared Clan Secret",
        "Ridiculous Petty Reason",
      ],
      laughmost: [
        "Blood",
        "Guts",
        "Pain",
        "Beheadings",
        "Hangings",
        "Drownings",
        "Begging",
        "Pleading",
        "Weeping",
        "Arson",
        "Larceny",
        "Vandalism",
        "Screams",
        "Gunfights",
        "Speeding",
        "Explosions",
        "Throttling",
        "Biting People",
        "Chemical Warfare",
      ],
      pelt: [
        "Dark and Coarse",
        "Pale and Downy",
        "Riven with Scars",
        "Greasy Spikes",
        "Brindled",
        "Mostly Burnt Off",
        "Long and Silky",
        "Short and Scratchy",
        "Purest White",
        "Mottled Brown",
        "Regal Silver",
        "Concrete Grey",
        "Curly and Rancid",
        "Dyed Blood Red",
        "Shaved into Stripes",
        "Midnight Black",
        "Muddy Brown",
        "Crawling with Parasites",
        "Thundercloud Blue",
        "Tigerish Stripes",
      ],
      teeth: [
        "Yellow Daggers",
        "Little Brown Nubs",
        "White and Gleaming",
        "Mostly Rotted Out",
        "One Gold Tooth",
        "Hooked and Grimy",
        "Chrome Implants",
        "Needle Thin",
        "Triple Row, Like a Shark",
        "Diamond Hard Gnashers",
        "Blunt and Black",
        "Just One Left",
        "Crooked Orange Spikes",
        "Engraved with Pictures",
        "Full of Holes",
        "Huge, Tusk-like",
        "Giant Underbite",
        "Rediculous Overbite",
        "Canted and Greying",
        "Weirdly Human",
      ],
      laugh: [
        "Raucous",
        "Whispery",
        "Machine-gun Barks",
        "Rusty Hinge",
        "Whooping",
        "Coughing",
        "Hissing Snicker",
        "Breathless",
        "Booming",
        "Hoarse and Strangled",
        "Maddening Gasps",
        "Wet Chuckles",
        "Turns into Hiccups",
        "Starts Quiet and Rises",
        "Joyless Giggling",
        "Pained",
        "Cold and Malevolent",
        "Childish and Cruel",
        "Could Wake the Dead",
        "Soundless but Horrid",
      ],
      attire: [
        "Human-Leather Jacket",
        "Translucent Plastic",
        "Greasy Rags",
        "Mock Wedding Clothes",
        "Gaudy Shawl",
        "Mock Religious Attire",
        "Unsettling Mask",
        "Harlequin's Motley",
        "Bloodstained Bandages",
        "Sun-faded Scraps",
        "Plastic Bags",
        "Iridescent Chains",
        "Purple Silks",
        "Mock Hegemony Uniform",
        "A Rival's Skin",
        "Spiked Shoulder-pads",
        "Soiled Hazmat Gear",
        "Peacock-Feather Cape",
        "Lizard-Skin Suit",
        "Nothing but Knives",
      ],
    },
  },
  Lithling: {
    ancestryName: "Lithling",
    sentenceTemplate:
      "You are a <a id='size'>SIZE</a> and <a id='body'>BODY</a> Lithling with a <a id='headcarving'>HEADCARVING</a> carving upon your head. Your skin is <a id='hue'>HUE</a>. You are <a id='manner'>MANNER</a>, and the esoteric subject you devote your life to is <a id='study'>STUDY</a>. Your quirk is <a id='quirk'>QUIRK</a>.",
    description:
      "Strange beings even by the standards of Vaarn, the Lithling are a slow, solemn species with a silicon-based biology that surely originates in a solar system far away from Urth. They are solitary by nature, concerned mainly with the opinions of other Lithling and the esoteric academic studies they devote their long lives to.</br></br>Adult lithling cannot repair their bodies when they have been injured, and so, although immortal by human standards, the creatures must treat every wound suffered with utmost severity.",
    abilities:
      "<span>CRYSTALLINE FLESH</span> - You are made from living crystal. Your minimum Armour Defense is 16. You do not need to eat or drink. You do not take damage from fire, cold, poison, radiation, electricity, fungal spores, or suffocation.</br></br><span>INEVITABLE</span> - During character generation, roll d8 and multiply the result by 100. This number is your starting HP. You cannot heal lost HP through any means, and do not add to your maximum HP when you gain a level. When your HP tally reaches zero you crumble into iridescent dust, leaving behind a pebble-sized lithling seed.",
    imageCount: 4,
    traits: {
      name: [
        "Aikin",
        "Antimony",
        "Bentor",
        "Brokenhill",
        "Cabalzar",
        "Cairngorm",
        "Chalcedony",
        "Diaspor",
        "Ephesi",
        "Heliotrope",
        "Idrial",
        "Indium",
        "Jaros",
        "Khatyr",
        "Meerschaum",
        "Okenit",
        "Qusong",
        "Schori",
        "Ulrich",
        "Ziest",
      ],
      size: [
        "Child-like",
        "Child-like",
        "Child-like",
        "Child-like",
        "Child-like",
        "Small",
        "Small",
        "Small",
        "Small",
        "Small",
        "Moderate",
        "Moderate",
        "Moderate",
        "Moderate",
        "Large",
        "Large",
        "Large",
        "Imposing",
        "Imposing",
        "Imposing",
      ],
      body: [
        "Dainty",
        "Tiny",
        "Boxy",
        "Voluptuous",
        "Squat",
        "Lithe",
        "Angular",
        "Craggy",
        "Elegant",
        "Bulbous",
        "Sharp",
        "Rotund",
        "Weathered",
        "Monumental",
        "Derelict",
        "Blocky",
        "Flaking",
        "Smooth",
        "Pitted",
        "Fragmented",
      ],
      headcarving: [
        "Sphere",
        "Owl",
        "Serpent",
        "Oxen",
        "Horse",
        "Warrior",
        "Maiden",
        "Locust",
        "Jackal",
        "Moon",
        "Sun",
        "Pyramid",
        "Cat",
        "Trout",
        "Scholar",
        "Fool",
        "Crone",
        "Mantis",
        "Ape",
        "Goat",
      ],
      hue: [
        "Rose",
        "Onyx",
        "Azure",
        "Silver",
        "Indigo",
        "Gold",
        "Violet",
        "Ruby",
        "Orange",
        "Topaz",
        "Jade",
        "Brass",
        "Copper",
        "Rust",
        "Moss",
        "Ochre",
        "Steel",
        "Sand",
        "Citrine",
        "Emerald",
      ],
      manner: [
        "Logical",
        "Obsessive",
        "Naive",
        "Abrasive",
        "Forgetful",
        "Aloof",
        "Mellow",
        "Sentimental",
        "Amoral",
        "Impulsive",
        "Negative",
        "Rigid",
        "Patient",
        "Decisive",
        "Gracious",
        "Assertive",
        "Unhurried",
        "Vengeful",
        "Graceless",
        "Stern",
      ],
      study: [
        "Shellfish",
        "Ants",
        "Spirals",
        "Cacti",
        "Birdsong",
        "Lizard Eggs",
        "Fingernails",
        "Shoes",
        "Wasps",
        "Land Snails",
        "Tarantulas",
        "Jackals",
        "Pottery",
        "Dance",
        "Lunar Cycles",
        "The Sun",
        "Tides",
        "Wind",
        "Rain",
        "Silence",
      ],
      quirk: [
        "Engraved with Poem",
        "Engraved with Curse",
        "Engraved with Map",
        "Engraved with Equation",
        "Plants Grow From Head",
        "Deep Crack in Face",
        "Covered in Moss",
        "Covered in Dead Vines",
        "Hollow Chest",
        "Hollow Head",
        "Eyes Glow in Dark",
        "Hand Missing",
        "Face Eroded Away",
        "Leaking Dust",
        "You Are Translucent",
        "Chest Filled With Fluid",
        "Holes Blasted in Flesh",
        "Second Face on Torso",
        "Mirrored Flesh",
        "Face Rotates",
      ],
    },
  },
  Planeyfolk: {
    ancestryName: "Planeyfolk",
    sentenceTemplate:
      "You are <a id='body'>BODY</a> and <a id='geometry'>GEOMETRY</a>, with <a id='hair'>HAIR</a> hair and a <a id='head'>HEAD</a> head. Your attire is <a id='attire'>ATTIRE</a>. You are <a id='demeanor'>DEMEANOR</a>, and you are a Planeyfolk because <a id='howflat'>HOWFLAT</a>.",
    description:
      "The study of hypergeometry claimed many casualties, for those who seek to unpick the stitches of creation do so at great risk. The slightest mistake in hypergeometic calculations could cause ghastly distortions of matter, birthing monstrosities of perspective and volume, the sight of which turned even the most courageous man into a coward.</br></br>Planeyfolk are the descendants of such unfortunates, a race fathered by men who slipped through the cracks of Euclidean space into something new and strange. Some have normal proportions, and can be mistaken for a true person when viewed head-on. Others are possessed of more exotic geometry, their forms warped by impossible vanishing points and blasphemous angles.",
    abilities:
      "<span>FLAT</span> - You lack a third dimension, and resemble a living painting or paper doll. You can slip through cracks and under doors, and cannot be seen from the side. You take halved damage from bludgeoning attacks, and double damage from slashing or piercing attacks.</br></br><span>ATTUNE WITH MATTER</span> - You struggle to hold 3D objects, and must make a DEX save to do so. However, with certain mental techniques you can draw 3D objects into your flattened reality. Given an hour of quiet concentration, you can attune yourself with an item, and add it to your inventory.",
    imageCount: 4,
    traits: {
      name: [
        "Clotho",
        "Atropos",
        "Osteria",
        "Vanise",
        "Whervil",
        "Laomer",
        "Foxglory",
        "Thelik",
        "Umbrie",
        "Salter",
        "Atlassia",
        "Eukelaris",
        "Galas",
        "Tarvi",
        "Untermance",
        "Rassias",
        "Menomeo",
        "Ithari",
        "Canetonus",
        "Trout",
      ],
      body: [
        "Fractured",
        "Cloven",
        "Flimsy",
        "Willowy",
        "Curved",
        "Elongated",
        "Staccato",
        "Blurred",
        "Ghostlike",
        "Draping",
        "Compressed",
        "Cubic",
        "Smeared",
        "Sharp",
        "Angular",
        "Prismatic",
        "Hollow",
        "Delicate",
        "Isometric",
        "Imposing",
      ],
      head: [
        "Impressionistic",
        "Broken",
        "Lantern-like",
        "Crescent Moon",
        "Full Moon",
        "Luminous",
        "Angular",
        "Fractal",
        "Hollow",
        "Shimmering",
        "Lurid",
        "Lustrous",
        "Rhomboid",
        "Figment",
        "Wide",
        "Elongated",
        "Helix",
        "Triangular",
        "Quadrilateral",
        "Fragmentary",
      ],
      hair: [
        "Flickering",
        "Insubstantial",
        "Curved",
        "Voluminous",
        "Opalescent",
        "Shaven",
        "Iridescent",
        "Lurid",
        "Fractal",
        "Polygonal",
        "Shard-like",
        "Triangular",
        "Splintering",
        "Dark",
        "Imposing",
        "Pale",
        "Cubic",
        "Polychromic",
        "Drifting",
        "Fragmentary",
      ],
      attire: [
        "Dark",
        "Unruly",
        "Scholarly",
        "Masked",
        "Wild",
        "Polychromic",
        "Fractal",
        "Glitching",
        "Gauzy",
        "Fragmented",
        "Mosaic-like",
        "Boxy",
        "Flamboyant",
        "Dour",
        "Striped",
        "Spotted",
        "Glass-like",
        "Concealing",
        "Barbaric",
        "Outrageous",
      ],
      demeanor: [
        "Anxious",
        "Arrogant",
        "Assertive",
        "Charismatic",
        "Conceited",
        "Decadent",
        "Eloquent",
        "Extravagant",
        "Hedonistic",
        "Impulsive",
        "Irritable",
        "Meticulous",
        "Persistent",
        "Quiet",
        "Religious",
        "Pugnacious",
        "Scholarly",
        "Stern",
        "Unruly",
        "Volatile",
      ],
      geometry: [
        "Cast Two Shadows",
        "Never Cast Shadows",
        "Move Like Stop-Motion Animation",
        "Your Face Appears Concave",
        "Your Face Appears Convex",
        "You Always Appear in Profile",
        "You Always Face Away From Observers",
        "One Limb is Enormously Long",
        "Viewed From Behind You Have No Skin",
        "Interiors Are Visible, But Cannot be Touched",
        "Hands Fractal; Tiny Hands on Ends of Fingers",
        "You Bleed Gory Cubes",
        "Your Body is Clearly Hollow",
        "Eyes Are Holes of Infinite Depth",
        "Voice Sounds As If You Are Far Away",
        "You Have No Back, Just Two Identical Fronts",
        "Head Looks Ten Times Larger Than Body",
        "Never Seem To Touch Anything",
        "Multiple Identical Faces",
        "You Never Match the Ambient Light",
      ],
      howflat: [
        "your Parents were Planeyfolk",
        "your Parents were Planeyfolk",
        "your Parents were Planeyfolk",
        "your Parents were Planeyfolk",
        "your Parents were Planeyfolk",
        "you were Exposed to hypergeometry in utero",
        "you were Exposed to hypergeometry in utero",
        "you were Cursed by Quantum Daemon",
        "you were Cursed by Quantum Daemon",
        "of a Malfunctioning longjaunt portal",
        "of a Malfunctioning longjaunt portal",
        "you Accidentally ate hypergeometric food",
        "you Accidentally ate hypergeometric food",
        "a Planeyperson inducted you into their dimension",
        "a Planeyperson inducted you into their dimension",
        "you Meditated before a 4D tesseract",
        "you Meditated before a 4D tesseract",
        "You were a hypergeometrician, there was an accident",
        "You were a hypergeometrician, there was an accident",
        "You were a hypergeometrician, there was an accident",
      ],
    },
  },
  // Add other ancestries here
};
